### ISSUE TITLE
More than 1 device with the same name is not supported

### ISSUE THREAD

**Issue by samhunt** [samhunt/homebridge-esphome-ts#4]
from @edrikk
> It appears that although the plugin allows for addition of more than one device, it doesn't differentiate between the devices - the accessories are just called "door" "light" etc. and as such only one of the 2 devices shows up in homebridge.
> Can see the the two devices appear to be discovered with same names for the accessories -- As a test I did successfully import both into Home Assistant, and exposed them to Homekit successfully...

**Comment by edrikk** [comment]
Hi thank you!

can I provide any further information to help expedite the 3 tickets?  Especially this one to be honest.

Thank you again for this!
